### ISSUE TITLE
Création marker  G-map

### ISSUE THREAD

**Issue by LCanix** [unip62/GoLilleOut#7]
Bonjour,
Lorsque je souhaite créer un événement, je dois cliquer une première fois sur le bouton placer événement puis créer événement, je trouve ça consternant qu'en 2016 avec Angular JS nous soyons obligé de faire ça. Surtout que nous payons un expert bien assez cher dans votre CDS.

Merci de modifier ça au plus vite pour respecter la demande MOA.

Cordialement,
Matthieu Saab

**Comment by unip62** [comment]
L'équipe de développement corrige ça au plus vite
